version: 2.1
orbs:
  node: circleci/node@5.0.1
  docker: circleci/docker@2.2.0
jobs:
  build:
    docker:
      - image: cimg/node:16.10
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run: |
          echo "Installing dependencies..."
          npm install
  test:
    docker:
      - image: cimg/node:16.10
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run: |
          echo "Running tests..."
          npm run test
  publish:
    docker:
      - image: cimg/node:16.10
        auth: 
          username: xong002
          password: Password1!
    steps:
      - setup_remote_docker:
          version: 20.10.14
          docker_layer_caching: true
      - run : |
          TAG=0.1.$CIRCLE_BUILD_NUM
          docker build -t circleci-demo:$TAG .
          echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
          docker push circleci-demo:$TAG   

workflows:
  simple_workflow:
    jobs:
      - build
      - test:
          requires:
            - build
      - publish:
          requires:
            - test
            - build            

