version: 2.1
orbs:
  node: circleci/node@5.0.1
  docker: circleci/docker@2.2.0
  heroku: circleci/heroku@2.0.0
jobs:
  build:
    docker:
      - image: cimg/node:16.10
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run: |
          echo "Installing dependencies..."
          npm install
  test:
    docker:
      - image: cimg/node:16.10
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run: |
          echo "Running tests..."
          npm run test
  publish:
    docker:
      - image: cimg/node:16.10
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.14
          docker_layer_caching: true
      - docker/check
      - docker/build:
          image: xong002/circleci-demo
          tag: <<pipeline.git.tag>>
      - docker/push:
          image: xong002/circleci-demo
          tag: <<pipeline.git.tag>>
  deploy:
      docker:
          - image: cimg/node:16.10
      steps:
          - setup_remote_docker      
          - heroku/install
          - checkout
          - run:
              name: Heroku Container Push
              command: | 
                  heroku container:login
                  heroku container:push web -a xinzhi-su-devops
                  heroku container:release web -a xinzhi-su-devops
workflows:
  simple_workflow:
    jobs:
      - build:
          filters:
            branches:
              only:        
                - main
      - test:
          filters:
            branches:
              only:        
                - main      
          requires:
            - build
      - publish:
          requires:
            - test
          filters:
            branches:
              ignore: /.*/
            tags:
              only: 
                - /^v.*/
      - deploy:
          requires:
            - publish
          filters:
            branches:
              ignore: /.*/
            tags:
              only: 
                - /^v.*/
